name: Build, Push and Update Helm

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: anshutruemeds/react-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # ---------- DOCKER LOGIN ----------
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---------- BUILD IMAGE ----------
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ github.run_number }} .
          docker tag $IMAGE_NAME:${{ github.run_number }} $IMAGE_NAME:latest

      # ---------- PUSH IMAGE ----------
      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:${{ github.run_number }}
          docker push $IMAGE_NAME:latest

      # ---------- UPDATE HELM VALUES ----------
      - name: Update Helm values.yaml
        run: |
          sed -i "s/tag:.*/tag: \"${{ github.run_number }}\"/" helm/frontend/values.yaml

      # ---------- COMMIT UPDATED HELM ----------
      - name: Commit and Push Helm changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/frontend/values.yaml
          git commit -m "Update image tag to ${{ github.run_number }}" || echo "No changes to commit"
          git push
