replicaCount: 3

image:
  repository: anshutruemeds/react-app
  tag: "20"
  pullPolicy: Always
  
ingress:
  enabled: true
  host: coreui.local
  
service:
  type: NodePort
  port: 80
  nodePort: 30009

